### ISSUE TITLE
Source install ROS

### ISSUE THREAD

**Issue by 130s** [start-jsk/qnx_ros#3]
A valid alternative to enabling `rosdep` ( #2 ), which @stefanmay seems to be [stuck at](https://groups.google.com/d/msg/ros-sig-embedded/cak1-QNevgo/VJQADx0Vzs0J).

**Comment by 130s** [comment]
It's nice if we will eventually be able to install the packages that are depended from `ROS` by `rosdep`, but at the moment we want to figure out if they build first all. So beginning from source installation sounds like a valid start point to me.

**Comment by emijah** [comment]
Sounds like a good idea

**Comment by stefanmay** [comment]
Dear Isaac,

I compiled every package of ros_comm (groovy) successfully on QNX (x86 
vmware image). How will you go on with this project? There are many 
things to adjust, but they seem to be manageable.

Best regards,

```
Stefan
```

Am 31.08.2013 04:26, schrieb Isaac Isao Saito:

**Comment by 130s** [comment]
Stefan, great to hear!

Although I don't think I'll need ROS on QNX very soon, I'll definitely try to build ros_comm on my qnx and provide feedback here or on wiki (It'll be next week after the exhibition will be over).

$At iREX, I've been asked a few times by people in industry if ROS runs on QNX and I mentioned that there's work being done. As certified for industrial use QNX capability seems to be compelling to some level at least. But ROS is not certified anyway and how we convince them or not is a whole new discussion.

**Comment by stefanmay** [comment]
Dear Isaac,

I've updated the wiki. I hope you can reproduce the whole installation 
of ros_comm.

There are still some remaining problems with the python scripts of ROS. 
roscore cannot be launch. You have to do it with rosmaster --core.
But then you can verify that the connection between QNX and another host 
is possible via ROS.

I hope the community will develop these findings further to have once 
the full functionality of ROS on QNX nodes. I'll leave it like that for 
the moment.
Besides, I verified whether rosserial is working on QNX. With a few 
modifications, it can be compiled and executed.

Best regards,

```
Stefan
```

Am 08.11.2013 10:18, schrieb Isaac Isao Saito:
